library(walkabilitysurvey)

# Loads all the files where functions are defined
files <- list.files(path = here::here("R"), pattern = "*.R", full.names = TRUE,
                    recursive = FALSE)
for (i in files) {
  source(i)
}


df <- data_preparations	("data/raw/survey_autogenerated.csv")



